#!/bin/bash
#
# This script is a wrapper which runs the Java application in a bash script with the needed options
#
exec $SNAP/bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/JNordVpnManager-2024.1.1.jar "$@"
