name: j-nordvpn-manager
version: '2024.1.0'
summary: Frontend for NordVPN Service
description: |
  Introducing JNordVPN Manager - a user-friendly, open-source graphical interface for managing NordVPN connections on Linux. This application simplifies VPN administration with features like a server/city list grouped by countries with filter functionality, connection management (login, logout, connect, disconnect, pause), and a world map showing all servers and the active one. Recent connections are also stored for easy reconnection by a single click.

grade: stable
confinement: devmode
base: core22

title: JNordVPNManager
website: https://github.com/com-mr-apps/JNordVPNManager
issues: https://github.com/frossm/com-mr-apps/JNordVPNManager/issues
license: CDDL-1.1
donation: https://buymeacoffee.com/3dprototyping
icon: snap/gui/JNordVPNManager.svg

# Enable faster LZO compression
compression: lzo

apps:
  j-nordvpn-manager:
    command: JNordVPNManager-starter
    plugs:
       - network

parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local

  j-nordvpn-manager:
    plugin: maven
    source: https://github.com/com-mr-apps/JNordVPNManager.git
    source-branch: main
#    source-tag: JNordVPNManager_2024_1_0
#    source_tag: trunk
    source-type: git
    
#    maven-parameters:
#      [-DskipTests=true, -Dsomarg=false]
       
    build-packages:
      - maven
      - openjdk-11-jdk-headless

    stage-packages:
      - openjdk-11-jre-headless
        
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
